- name: Update apt cache
  apt:
    update_cache: yes

- name: Configure auto patching
  copy:
    src: 50-unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Patch the system
  apt:
    name: "*"
    state: latest

- name: Clean up unused packages
  apt:
    autoremove: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true