- name: Check if Zabbix agent is already installed
  stat:
    path: /etc/zabbix
  register: zabbix_installed

- name: Copy Zabbix package
  copy:
    src: zabbix-release_6.2-2+ubuntu22.04_all.deb
    dest: /tmp/zabbix-release_6.2-2+ubuntu22.04_all.deb
  when: not zabbix_installed.stat.exists

- name: Install Zabbix package
  apt:
    deb: /tmp/zabbix-release_6.2-2+ubuntu22.04_all.deb
  when: not zabbix_installed.stat.exists

- name: apt update
  apt:
    update_cache: yes

- name: Install Zabbix Agent 2
  apt:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix Agent 2
  template:
    src: zabbix_agent2.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: 0660

- name: Configure apt update checks
  copy:
    src: apt.conf
    dest: /etc/zabbix/zabbix_agent2.d/apt.conf
    owner: zabbix
    group: zabbix
    mode: 0660

- name: Configure zabbix agent PSK
  copy:
    src: zabbix-agent-psk
    dest: /etc/zabbix/zabbix-agent-psk
    decrypt: yes
    owner: zabbix
    group: zabbix
    mode: 0660

- name: Add Zabbix user to Docker group
  user:
    name: zabbix
    groups: docker

- name: Restart and enable Zabbix Agent 2 service
  systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes

- name: Fix iptables so it works
  command: iptables -I INPUT -j ACCEPT

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4